now in sync with blaise-database
ONSdigital/blaise-case-processor pull request #34
Opened 2020-08-13 13:27 UTC by elthorne

2020-08-17 13:17 UTC, elthorne commented
Per Matthew's instructions I:

* Uploaded a sample in dev-el-22 and deployed the cases
* Published a message (example: https://github.com/ONSdigital/blaise-case-auto-complete) to the autocomplete-cases topic
* ran validation from this hidden page: https://dev-el-22-bsm.social-surveys.gcp.onsdigital.uk/validation/overall_summary
* logs and this page (https://dev-el-22-bsm.social-surveys.gcp.onsdigital.uk/case_details/case_details?case_id=2001&previous=%2Fcases%2Fcase_summary_by_instrument%3Finstrument_id%3D1) confirms no errors

2020-08-25 08:20 UTC, anax32 commented on blaise_case_processor/models.py
> +    case_id = Column(Integer(), ForeignKey('case.id', ondelete='cascade'), index=True)
check if the delete cascade is a business requirement.

2020-08-25 08:20 UTC, anax32 commented on blaise_case_processor/models.py
> +    primary_key = Column(String(255))
why is there a primary_key field and an id field which is a primary_key?

2020-08-25 08:20 UTC, anax32 commented on blaise_case_processor/models.py
> +    binding = Column(String(255))
It is difficult to follow this change because the block has been moved; what was the reason for moving the block?

2020-08-25 08:20 UTC, anax32 commented on blaise_case_processor/models.py
> +    date_created = Column(DATETIME())
this change is difficult to read because the blocks have moved; is the only change the addition of a ForeignKey and delete cascade?

2020-08-27 09:48 UTC, pds2208 requested changes

2020-08-27 09:48 UTC, pds2208 commented on blaise_case_processor/models.py
> +    # sample_id = Column(Integer(), ForeignKey('sample.id', ondelete='cascade'), index=True)
Do we need this comment?

2020-08-27 09:48 UTC, pds2208 commented on blaise_case_processor/models.py
> +    case_id = Column(Integer(), ForeignKey('case.id', ondelete='cascade'), index=True)
Do we delete the case history anywhere?

2020-08-27 09:48 UTC, pds2208 commented on blaise_case_processor/models.py
> +    # mi_spec = Column(Integer(), ForeignKey('mi_spec.id'), index=True)
Why are we deleting the foreign key?

2020-08-27 09:48 UTC, pds2208 commented on blaise_case_processor/models.py
> +    mi_spec = Column(Integer(), index=True)
mi_spec needs to be a foreign key

2020-08-27 09:48 UTC, pds2208 commented on blaise_case_processor/models.py
> +    sample_id = Column(Integer(), index=True)
Why remove the foreign key?

2020-08-27 09:48 UTC, pds2208 commented on blaise_case_processor/models.py
> +    case_id = Column(Integer(), ForeignKey('case.id', ondelete='cascade'), index=True)
Deleting the case if we delete the history is probably not what we want

2020-08-27 09:52 UTC, elthorne commented on blaise_case_processor/models.py
> +    primary_key = Column(String(255))
because Blaise

2020-08-27 09:52 UTC, elthorne commented on blaise_case_processor/models.py
> +    binding = Column(String(255))
it made it easier to do a visual comparison between this model and the models produced by the database

2020-08-27 09:57 UTC, elthorne commented on blaise_case_processor/models.py
> +    mi_spec = Column(Integer(), index=True)
that foreign key was excluded because it has a relationship with a table that isn't used by blaise-case-processor. I would have to include that table in the model as well as all other subsequent tables that have relationships; tables that aren't used by blaise-case-processor

2020-08-27 09:57 UTC, elthorne commented on blaise_case_processor/models.py
> +    sample_id = Column(Integer(), index=True)
that foreign key was excluded because it has a relationship with a table that isn't used by blaise-case-processor. I would have to include that table in the model as well as all other subsequent tables that have relationships; tables that aren't used by blaise-case-processor

2020-08-27 09:59 UTC, pds2208 approved these changes

2020-08-27 09:59 UTC, merged